

#+TITLE: Solving Quadratic Equations
#+AUTHOR: Rawley Amankwah
#+DATE: 30/07/2024
#+OPTIONS: toc:nil


"We do not learn mathematics, we just get used to it" - Amankwah Rawley

A Quadratic Equation is a polynomial equation of the form $ax^2 + bx + c = 0$ (A polynomial of order 2). There are several ways to solve quadratic equations. This
article will elaborate on **three** methods. They are:
- Factorization
- Completing of Squares
- Quadratic Formula


* Factorization
Given a quadratic equation $ax^2 + bx + c = 0$. The factorization method says
- Find the factors of c (including negative values).
- Find two factors of c such that they multiply to give c and sum to give b.
- Substitute the two factors for b
- Group the terms in Twos
- Then Factorize

** Example
Consider the following quadratic equation: $x^2 + 5x + 6 = 0$
Firstly we recognize that $a=1, b=5, c=6$
Using the Factorization method
- Find the factors of the c=6
(Factors simply means integers which can divide c exactly without a remainder)
The factors of c are ${-3,-2,-1,1,2,3,6}$

- Finding two factors of c such that they multiply to give c=6 and sum to give b=5
Intuitively, we recognize the satisfying factors are ${3,2}$ because $3\times 2 = 6$ and $3+2 = 5$

- Substituting the two factors for b
$x^2 + 5x + 6 = 0$ \\
$x^2 + 3x + 2x + 6 = 0$ \\ 
$(x^2 + 3x) + (2x + 6) = 0$ \\

- Then Factorizing
We recognize that the first group has coefficients ${1,3}$ and the second group ${2,6}$ \\
For each group we find the greatest common divisor: \\
The greatest common divisor or (Highest common divisor (HCF)) for the first group is $1$ and the second group is $2$ \\
$1x(x + 3) + 2(x + 3) = 0$ \\
Whenever one uses the factorization method, one has to get similar values in both brackets at this point, else \\
it means, there was an error \\
We group the values outside the brackets into one bracket, and we pick one of the duplicate brackets $(x+3)$ \\
$(x+2)(x+3) = 0$ \\
To find the solution, we simply equate each bracket to 0 \\
$x+2 = 0$ \\
$x=-2$ \\
or \\
$x+3 = 0$ \\
$x=-3$ \\

** Example 2
Consider the following quadratic equation: $x^2 -5x + 6 = 0$ \\
**Note** This example is different from the above example because: \\
Firstly we recognize that $a=1, b=-5, c=6$ \\
**Note** b is -5 instead \\
Using the Factorization method: \\
- Find the factors of the c=6 
The factors of c are ${-3,-2,-1,1,2,3,6}$ \\

- Finding two factors of c such that they multiply to give c=6 and sum to give b=-5
Intuitively, we recognize the satisfying factors are ${-3,-2}$ because $-3\times -2=6$ and $-3+(-2)=-5$ \\

- Substituting the two factors for b
$x^2 -5x + 6 = 0$ \\
$x^2 - 3x + -2x + 6 = 0$ \\
$(x^2 - 3x) + (-2x + 6) = 0$ \\
Factorizing by finding the HCF or greatest common divisor \\
$x(x - 3) + -2(x - 3) = 0$ \\
We are happy, because the two brackets are the same. \\
We group the values outside of the brackets into a bracket and pick one of the duplicated bracket \\
$(x - 2)(x-3) = 0$ \\
To find the solution (roots), we equate the each bracket to 0 \\
$x - 2 = 0$ \\
$x = 2$ \\
or \\
$x - 3 = 0$ \\
$x = 3$ \\

*** Exercises
Use the Factorization method to find the solution to the following quadratic equations: \\
- $x^2 - 10x + 21=0$ solution ${x =3, x=7}$ \\
- $2x^2 + 5x - 12 = 0$ solution ${x=3/2, x=-4}$ \\
- $x^2 - 3x - 10 = 0$ solution ${x=5, x=-2}$ \\


* Completing of Squares
"Completing of Squares" is another method of solving quadratic equations. It is rarely used in solving quadratic equation. \\
However, one ought to be equipped with this knowledge, just in case, your teacher asks you to apply only this method. Apply the \\
following steps in solving with the completing of squares method. \\

Consider the general form of the quadratic equation: $ax^2 + bx + c=0$ \\ 
Then: \\
- Divide the entire equation by a so that the coefficient of $x^2$ is 1 \\
 $x^2 + (b/a)x + c/a = 0$ \\
- Multiply the coefficient of the middle term by half (1/2), square and subtract the result from itself \\
 $x^2 + (b/a)x + (b/2a)^2 - (b/2a)^2 + c/a = 0$ \\
 Note: The equation remains the same, we just added 0 (i.e the result of the third and fourth terms above) \\
- Group the first and third term together without their squares \\
 $(x + (b/2a))^2 - (b/2a)^2 + c/a = 0$ \\
 Note: When we expand the first bracket, we always get the result of the step above \\
- Rearranging the equation \\
 $(x + (b/2a))^2 = (b/2a)^2 - c/a$ \\
- Solving the Right Hand Side of the equation, we get  \\
 $(x + (b/2a))^2 = b^2/4a^2 - c/a$ \\
 $(x + (b/2a))^2 = (b^2 - 4ac)/4a^2$ \\
- Square root both sides to get \\
 $(x + (b/2a)) = \sqrt((b^2 - 4ac)/4a^2)$ \\
 Note: the square root of a value, yields both a negative and a positive result \\
 $x = (-b/2a) \pm \sqrt((b^2 - 4ac)/4a^2)$ \\
 $x = (-b/2a) \pm \sqrt(b^2 - 4ac)/2a$ \\
 $x = \dfrac{(-b \pm \sqrt(b^2 - 4ac))}{2a}$ \\
 The above equation is referred to as the "Quadratic formula" \\

** Example
Consider the following quadratic equation: $4x^2 - 5x - 12 = 0$. Use the Completing of
squares method to solve it. \\

$4x^2 - 5x - 12 = 0$ \\
$a= 4, b = -5, c = -12$ \\
- Making the coefficient of x^2 one 
$x^2 + (-5/4)x - 3 = 0$ \\
- Multiplying the coefficient of the middle term by half (1/2), square and subtracting the result from itself
$x^2 + (-5/4)x + ((1/2)(-5/4))^2 - ((1/2)(-5/4))^2 - 3 = 0$ \\
$x^2 + (-5/4)x + (-5/8)^2 - (-5/8)^2 - 3 = 0$ \\
- Grouping the first and third term together without their squares
$(x + (-5/8))^2 - (-5/8)^2 - 3 = 0$ \\
- Rearranging the equation 
$(x + (-5/8))^2 = 3 + (-5/8)^2$ \\
$(x + (-5/8))^2 = 3 + 25/64$ \\
$(x + (-5/8))^2 = 217/64$ \\
- Taking the square root on both sides
$(x + (-5/8)) = \sqrt(217/64)$ \\
$x = 5/8 \pm \sqrt(217/64)$ \\
- Taking the positive sign "+"
$x = -1.216$ \\
- Taking the negative sign "-"
$x = 2.466$ \\
Therefore our solution(roots) are $x = {-1.2166, 2.466}$ \\

*** Exercises
Refer to the exercises above and use the completing of squares method to solve them \\

* Quadratic Formula
Quadratic Formula is one of the most common method for solving a quadratic equation especially when 
the coefficients are in decimals and factors are not easily found to use the factorization approach.
We use the following formula to solve a quadratic equation. \\

$x = (-b \pm \sqrt(b^2 - 4ac))/2a$ \\
This formula is known as the Quadratic Formula or the Almighty Formula (Do not ask me why)
We simply apply the formula to find the solution or roots of the quadratic equation \\

** Example
Consider the following quadratic equation $3x^2 - 5x + 2 = 0$ \\

We first note the coefficients, $a = 3, b = -5, c = 2$ \\
Then we substitute them into the formula \\ 
$x = \dfrac{(-(-5) \pm \sqrt((-5)^2 - 4(3)(2)))}{2(3)}$ \\
$x = (5 \pm \sqrt(25 - 24))/6$ \\
$x = (5 \pm \sqrt(1))/6 = (5 \pm 1)/6$ \\
Taking the positive sign \\
$x = (5 + 1)/6 = 1$ \\
Taking the negative sign \\
$x = (5 - 1)/6 = 2/3$ \\
Therefore the roots of the quadratic equation are {1, 2/3} \\

*** Exercise
Refer to the exercises above and use the quadratic formula to solve them. \\

Hopefully this short article has been helpful. \\
